CREATE DATABASE CompanyDB;
GO

USE CompanyDB;
GO

-- 1. EMPLOYEE Table
CREATE TABLE EMPLOYEE (
    Ssn CHAR(9) NOT NULL,
    Fname VARCHAR(15) NOT NULL,
    Minit CHAR(1) NULL,
    Lname VARCHAR(15) NOT NULL,
    Bdate DATE NULL,
    Address VARCHAR(30) NULL,
    Sex CHAR(1) NULL,
    Salary DECIMAL(10, 2) NULL,
    Super_ssn CHAR(9) NULL,
    Dno INT NULL,
    
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Ssn),
    CONSTRAINT CHK_Employee_Salary CHECK (Salary > 0),
    CONSTRAINT CHK_Employee_Sex CHECK (Sex IN ('M', 'F'))
);


-- 2. DEPARTMENT Table
CREATE TABLE DEPARTMENT (
    Dname VARCHAR(25) NOT NULL,
    Dnumber INT NOT NULL,
    Mgr_ssn CHAR(9) NOT NULL,
    Mgr_start_date DATE NULL DEFAULT GETDATE(),
    
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Dnumber),
    CONSTRAINT UQ_Department_Dname UNIQUE (Dname)
);

-- 3. DEPT_LOCATIONS Table
CREATE TABLE DEPT_LOCATIONS (
    Dnumber INT NOT NULL,
    Dlocation VARCHAR(15) NOT NULL,
    
    CONSTRAINT PK_DEPT_LOCATIONS PRIMARY KEY (Dnumber, Dlocation)
);

-- 4. PROJECT Table
CREATE TABLE PROJECT (
    Pname VARCHAR(25) NOT NULL,
    Pnumber INT NOT NULL,
    Plocation VARCHAR(15) NULL,
    Dnum INT NOT NULL,
    
    CONSTRAINT PK_PROJECT PRIMARY KEY (Pnumber),
    CONSTRAINT UQ_Project_Pname UNIQUE (Pname)
);

-- 5. WORKS_ON Table
CREATE TABLE WORKS_ON (
    Essn CHAR(9) NOT NULL,
    Pno INT NOT NULL,
    Hours DECIMAL(4, 1) NULL,
    
    CONSTRAINT PK_WORKS_ON PRIMARY KEY (Essn, Pno),
    CONSTRAINT CHK_WorksOn_Hours CHECK (Hours >= 0.0)
);

-- 6. DEPENDENT Table 
CREATE TABLE DEPENDENT (
    Essn CHAR(9) NOT NULL,
    Dependent_name VARCHAR(15) NOT NULL,
    Sex CHAR(1) NULL,
    Bdate DATE NULL,
    Relationship VARCHAR(20) NULL,
    
    CONSTRAINT PK_DEPENDENT PRIMARY KEY (Essn, Dependent_name),
    CONSTRAINT CHK_Dependent_Sex CHECK (Sex IN ('M', 'F')) 
);
GO

-- FOREIGN KEYS
-- Employee foreign keys
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_SUPERVISION 
    FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn) 
    ON DELETE NO ACTION;

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_WORKS_FOR 
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber);

-- Department foreign keys
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_MANAGES 
    FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn);

-- Dept_Locations foreign keys
ALTER TABLE DEPT_LOCATIONS ADD CONSTRAINT FK_DEPT_LOCATIONS_DEPARTMENT 
    FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber) 
    ON DELETE CASCADE;

-- Project foreign keys
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_CONTROLS 
    FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(Dnumber);

-- Works_On foreign keys
ALTER TABLE WORKS_ON ADD CONSTRAINT FK_WORKS_ON_EMPLOYEE 
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn) 
    ON DELETE CASCADE;
ALTER TABLE WORKS_ON ADD CONSTRAINT FK_WORKS_ON_PROJECT 
    FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber);

-- Dependent foreign keys
ALTER TABLE DEPENDENT ADD CONSTRAINT FK_DEPENDENT_DEPENDENTS_OF 
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn) 
    ON DELETE CASCADE;
GO

-- 5 INSERT STATEMENTS
-- 1. Insert a Manager Employee
INSERT INTO EMPLOYEE (Ssn, Fname, Minit, Lname, Bdate, Address, Sex, Salary, Super_ssn, Dno)
VALUES ('987654321', 'James', 'E', 'Borg', '1965-11-10', '450 Stone Rd, Houston, TX', 'M', 55000.00, NULL, NULL);

